// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eaviwtddflhdaomywqtl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhdml3dGRkZmxoZGFvbXl3cXRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MTMwOTcsImV4cCI6MjA2MjE4OTA5N30.geKYP8-NS2J9gJtGZ55RO4sC_poKR4WgGbDfRBdd6eo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);